name: Discord Alert

on:
  push:
    branches:
      - main

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"content": "🚀 Novo push no repositório! [Acesse o Discord](https://discord.gg/1366508867349123082)"}' \
          https://discord.com/api/webhooks/1366508867349123082/u9RiR0-Dfyx4t1bHtDP3CLr4it9Q5YJip4zlGDqoJYaGAgZt9PvTehB4r8ooXmjb-3cY
